# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

permalink:           pretty
# relative_permalinks: true

plugins:
  - jekyll-paginate


# Setup
title:               JH Park
tagline:             'note'
description:         'my programming note'
url:                 https://jeonghopark.github.io
baseurl:             ''
paginate:            5
future:              true


markdown: kramdown

kramdown:
  input: GFM



# About/contact
author:
  name:              jeongho park
  url:               http://jeonghopark.de
  email:             jeonghopark@jeonghopark.de

# Custom vars
version:             1.0.0
